function [BW_out,properties] = filterRegions(BW_in)
% Copyright (c) 2015, MathWorks, Inc.
%filterRegions  Filter BW image using auto-generated code from imageRegionAnalyzer app.
%  [BW_OUT,PROPERTIES] = filterRegions(BW_IN) filters binary image BW_IN
%  using auto-generated code from the imageRegionAnalyzer App. BW_OUT has
%  had all of the options and filtering selections that were specified in
%  imageRegionAnalyzer applied to it. The PROPERTIES structure contains the
%  attributes of BW_out that were visible in the App.

% Auto-generated by imageRegionAnalyzer app on 19-Oct-2015
%---------------------------------------------------------

BW_out = BW_in;

% Filter image based on image properties.
BW_out = bwpropfilt(BW_out, 'Area', [5000 + eps(5000), Inf]);

% Get properties.
properties = regionprops(BW_out, {'BoundingBox','Area'});

% Uncomment the following line to return the properties in a table.
% properties = struct2table(properties);
