#!/bin/bash

echo "VT_GPUTRACE=yes VT_METRICS=PAPI_L3_TCM VT_CUPTI_METRICS=active_warps:active_cycles OMP_NUM_THREADS=6 PSI_TPP=12 mpiexec -np 2 --exports=PATH,LD_LIBRARY_PATH,OMP_NUM_THREADS,PSI_TPP,VT_GPUTRACE,VT_BUFFER_SIZE,VT_METRICS,VT_CUPTI_METRICS $*"
VT_GPUTRACE=yes VT_METRICS=PAPI_L3_TCM VT_CUPTI_METRICS=active_warps:active_cycles OMP_NUM_THREADS=6 PSI_TPP=12 mpiexec -np 2 --exports=PATH,LD_LIBRARY_PATH,OMP_NUM_THREADS,PSI_TPP,VT_GPUTRACE,VT_BUFFER_SIZE,VT_METRICS,VT_CUPTI_METRICS $*
